[workspace]
resolver = "1"

members = [
    "pubhub-rs",
    "datetime-producer",
    "hwinfo-producer",
    "randint-producer",
    "test-client",
    "test-listener"
]

[profile.release]
opt-level = "z"  # Optimize for size.
strip = true